spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/playground?serverTimezone=UTC&characterEncoding=UTF-8
    username: playground-app
    password: 20230280
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

server:
  port: 8432

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
