server:
  port: 8000

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=playground;encrypt=false;
    username: playground_app
    password: namookk01!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


greeting:
  message: Welcome